// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "brand": { "alt": string }; "greetings": Array<{ "headline": string; "body": string; "id": string }>; "button": string; "footer": string; "detail": string } };
  export const home: { "brand": { "alt": string }; "greetings": Array<{ "headline": string; "body": string; "id": string }>; "button": string; "footer": string; "detail": string };
}
